services:
  api-v1:
    build: .
    container_name: fraud-api-v1
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_VERSION=v1

  api-v2:
    build: .
    container_name: fraud-api-v2
    ports:
      - "8001:8000"   # Port diff√©rent
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_VERSION=v2
